= Sky Drone 200 =

== About the Project ==
Based on our existing 'Drone-in-a-Box' solution, a prototype for a smaller system shall be developed.

Design Goals:

- Small UAV with a maximum takeoff weight of 250g.
- Weatherproof (IP43)
- Optimized for best-in-class range/endurance
- Mechanically simple base station that can be deployed either fixed or moving on a vehicle
- Potentially have a Network of Charging stations to go from station to station and have a 'swarm' of small drones.

Target Use:

- Quick aerial intelligence from a system deployed on a rescue vehicle that can be operated from remote command center
- Surveying & Mapping

== Project Timeline and Milestones ==

Time Frame: 2020-06-15 to 2020-09-30

=== Milestone 1 - Fly a prototype based on off-the-shelf components and standard airframe. ===
Due: 2020-07-15

- Different component options and off-the-shelf airframes need to be chosen and assembled into a flyable prototype.
- Iterate on components to incrementally improve performance, flight characteristics and optimize for target constraints (e.g. weight) by doing test flights.
- Familiarize with our technology to control a drone via 4G/5G as well as via 'traditional' remote control.

=== Milestone 2 - Custom Airframe and Base Station Design ===
Due: 2020-08-15

- Based on real-world testing insights gained in the previous project part, a custom airframe has to be designed which will then be manufactured and tested.
- In collaboration with our mechanical engineer - develop a base station design optimized for the custom airframe.
- Familiarize with our Simulation Environment ('Gazebo') and import/design the custom drone model in the Simulation Environment.

=== Milestone 3 - Validation ===
Due: 2020-09-15

- Validation of custom design and performance assumptions by documenting flight tests including edge conditions (high winds, rain, etc.).
- Optimization of the design based on test results.

=== Milestone 4 - Project Documentation ===
Due: 2020-09-30

- Document the project, reflect on issues and possible future improvements.
- 'Clean up' all project related files and documents for easy use by others.

== UAV ==

Core Components:

- flight controller
- motor controller (4-in-1)
- Sky Drone Core Compute Board
- Sky Drone Charging Controller
- downward facing camera
- front facing camera
- RTK-GPS module
- RTK-GPS antenna
- 4 motors
- 4 props
- Battery
- 4G/5G Antennas
- Gimbal / Gimbal Controller? (see below)

=== Reference projects ===

What is possible with a small drone?

33g drone "Black Hornet":

- https://www.flir.asia/products/black-hornet-prs/
- https://www.youtube.com/watch?v=rm_xMuo2Ong

250g drone reference projects:

- Expert on long range 250g drones: https://www.youtube.com/user/F4EIZ/videos
- https://www.youtube.com/watch?v=IGhF0htffao&feature=youtu.be
- https://www.youtube.com/watch?v=IJXYMGN1wzQ
- https://www.youtube.com/watch?v=butx8hOn3Ic

250g consumer drone:

- https://www.dji.com/hk/mavic-mini
- https://www.youtube.com/watch?v=hS_OjalEpZI

=== Feasability of a Gimbal solution ===

The drone will have two camera, one downward facing camera and one front facing camera.
If the weight budget allows, it would be ideal to have a 2-axis gimbal supporting the front camera.

Resources:

- "gimbal is possible in 250g frame" https://www.rcgroups.com/forums/showthread.php?2731761-Challenge-build-Sub-250g-aerial-photography-quad-with-brushless-gimbal
- "Without the gimbal, with a GF5030 props, the quad weights only 110g. With a 2s 3000mah li-on , flight time is between 50 and 60min."
- https://jeanleflambeur.wordpress.com/2016/08/29/gimbal/
- https://github.com/jeanleflambeur/silkopter/tree/master/printing/gimbal
- https://es.aliexpress.com/store/product/2-x-2204-260kv-Motor-1-x-2805-140kv-Brushless-Gimbal-Motor-for-3-Axis-Brushless/727847_32561221044.html?spm=2114.04010208.3.1.VR03rn&ws_ab_test=searchweb201556_0,searchweb201602_5_10057_10065_10056_10055_10054_10044_10043_301_10033_10059_10032_10058_10017_107_10041_10042_10060_10061_10052_414_10062_10053_10050_10051,searchweb201603_4&btsid=6e73e13e-f77b-4c83-ab78-d2f3cc0a94a9

== Base Station ==

Considerations:

- 12V power supply (usable on a vehicle)
- RTK GPS (use on vehicle)
- 4G/5G connected
- miniminze number of actuators required
- ability to firmly hold the drone (e.g. vehicle use)
- low power (can be solar powered with small panel/buffer battery)

